### ISSUE TITLE
Dumb question but...

### ISSUE THREAD

**Issue by bbecausereasonss** [shinomakoi/magi_llm_gui#1]
How do you load a model?

**Comment by shinomakoi** [comment]
To load a llama.cpp model, enter or select the path to the *.bin model file in 'llama.cpp: Model path' in the Settings tab.

To load a model for Exllama, select the folder containing the model in "Exllama: Model directory". The folder should contain the config.json and tokenizer.json files as well as the model file. I think it needs to be a GTPQ model too. 

Click save to remember the paths, and maybe restart the app.

**Comment by bbecausereasonss** [comment]
Thanks, do I need WSL for this or can this run in windows?

**Comment by shinomakoi** [comment]
It runs on Windows, but Exllama seems to be a pain right now, see: https://github.com/turboderp/exllama/issues/33
Llama.cpp should work on Mac but it seems the GPU acceleration hasn't been added to llama-cpp-python yet, but should be coming in the next release (https://github.com/abetlen/llama-cpp-python/issues/317)

**Comment by bbecausereasonss** [comment]
On Ubuntu/WSL seems It's missing a plethora of dependencies related to QT and others. Pretty tough to figure out.

**Comment by bbecausereasonss** [comment]
On Ubuntu/WSL seems It's missing a plethora of dependencies related to QT and others.

**Comment by shinomakoi** [comment]
Did you install the dependencies with `pip install -r requirements.txt` (in magi_llm_gui folder)

**Comment by bbecausereasonss** [comment]
I had yea

**Comment by bbecausereasonss** [comment]
Got it working! works well. Would be awesome if we could edit all the settings like context size, temperature top p etc in the UI.

**Comment by shinomakoi** [comment]
Nice. You can change the parameters in File > Parameters. I'll add save parameters and presets soon
