### ISSUE TITLE
Minor issue: path syntax for activating venv on Windows

### ISSUE THREAD

**Issue by BlackDragonBE** [shinomakoi/magi_llm_gui#10]
Your venv instructions for Windows are:
`./.magi-venv/Scripts/activate ### For Windows`

But the correct syntax is:
`.\.magi_venv\Scripts\activate ## For Windows`

Super small issue, but it will give an error otherwise: 
```
./.magi-venv/Scripts/activate : The term './.magi-venv/Scripts/activate' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
```

**Comment by shinomakoi** [comment]
Ah good catch, I have corrected it.
