### ISSUE TITLE
Unable to choose diff model without restart.

### ISSUE THREAD

**Issue by bbecausereasonss** [shinomakoi/magi_llm_gui#11]
We need a way to unload current model and load new model without restarting entire server/interface. ie) new exlamma or new cpp etc.

**Comment by shinomakoi** [comment]
Yeah this would be nice, but I fear it won't be easy to implement. I'll look into it

**Comment by shinomakoi** [comment]
I have added this now. rwkv.cpp doesn't seem to free the GPU memory when you unload but exllama and llama.cpp seem to work fine.
