### ISSUE TITLE
Does LlammaCPP use new KQuants and OpenCBlast?

### ISSUE THREAD

**Issue by bbecausereasonss** [shinomakoi/magi_llm_gui#5]
New KoboldCPP has Cuda offloading through CLBlast... Would be awesome to have this hear as well and KQuant support :)

**Comment by shinomakoi** [comment]
Yes these are supported, I use it with CUBLAS. But for CLBlast etc you need to compile it youself, see: https://github.com/abetlen/llama-cpp-python/#installation-from-pypi-recommended

I'll see if I can add pre-compiled versions

**Comment by bbecausereasonss** [comment]
I've got a 4090, do you think CLBlast would be faster than CUBLAS?

**Comment by bbecausereasonss** [comment]
Another question, I can use this on my M1 Mac /w Python (Metal) as well so long as I compile CPP for Metal?

**Comment by shinomakoi** [comment]
Nice, I bet Exllama is fast with a 4090. I imagine CUBLAS will be fastest, not tried CLBLAS though. 

Yeah the app should work on a Mac in theory but I haven't tried it. Hopefully it will

**Comment by bbecausereasonss** [comment]
Exllama is blazing fast with a 4090.
