### ISSUE TITLE
Errors crash app.

### ISSUE THREAD

**Issue by bbecausereasonss** [shinomakoi/magi_llm_gui#7]
Anytime I run into any type of error/limit, the UI crashes. ie) 2049 tokenlimit exceeded. Have to restart the whole app.

--- Launched app
--- Loading Exllama model...
INFO: Could not find files for the given pattern(s).
Injected compiler path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64
--- Exllama model: E:\Backups\Deep Models\LLama\models\TheBloke_robin-33B-v2-GPTQ\robin-33b-GPTQ-4bit--1g.act.order.safetensors
--- Exllama model load parameters: {'model_path': 'E:/Backups/Deep Models/LLama/models/TheBloke_robin-33B-v2-GPTQ', 'gpu_split': False}
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 70, in run
    backend_method()
  File "C:\Users\xxxx\Deep\magi\magi_llm_app.py", line 82, in run_exllama
    for response in responses:
  File "C:\Users\xxxx\Deep\magi\exllama_generate.py", line 151, in generate_with_streaming
    token = generator.gen_single_token()
  File "C:\Users\xxxx\Deep\magi\exllama\generator.py", line 268, in gen_single_token
    logits = self.model.forward(self.sequence[:, -1:], self.cache)
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 760, in forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device])
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 367, in forward
    self.self_attn.fused(hidden_states, cache, buffer, self.input_layernorm)
  File "C:\Users\xxxx\Deep\magi\exllama\model.py", line 254, in fused
    key_states = cache.key_states[self.index].narrow(2, 0, past_len + q_len)
RuntimeError: start (0) + length (2049) exceeds dimension size (2048).

**Comment by shinomakoi** [comment]
Yeah proper error handling is lacking, I'll sort that out. And implement a way to to prevent tokens exceeding the limit.

**Comment by bbecausereasonss** [comment]
Right now this is probably the biggest error preventing daily use of the software. I'm getting this quite a bit as the context grows. Otherwise, love the speed + simplicity

**Comment by shinomakoi** [comment]
Ah I didn't realise llama.cpp did it too. This should be properly fixed now, for llama_cpp_python and Exllama I implemented a system that auto trims context from the start if it exceeds the limit.

**Comment by bbecausereasonss** [comment]
Going to test.

**Comment by shinomakoi** [comment]
Fixed a bug with the Exllama prompt trimming, seems to work now
